Strings and Boxed types should be compared using "equals()"
apache/sling-org-apache-sling-scripting-esx pull request #1
Opened 2019-11-07 13:19 UTC by HarisAdzemovic

This fixes 2 Sonarqube violations of rule S4973:
https://rules.sonarsource.com/java/RSPEC-4973

Sonarcloud violation URL:
https://sonarcloud.io/organizations/apache/issues?languages=java&open=AWoocNf3MflNeiYSIfWd&resolved=false&rules=squid%3AS4973&types=BUG

Jira Ticket:
https://issues.apache.org/jira/browse/SLING-8825

2019-11-08 12:07 UTC, rombert requested changes

2019-11-08 12:07 UTC, rombert commented on src/main/java/org/apache/sling/scripting/esx/Module.java
> +            if (parts[i].equals("node_modules") || parts[i].equals("esx_modules")) {
Could you invert the check here so that the constants come first? Slightly better style and protects against NPEs (although I don't think that's the case here).

2019-11-08 13:44 UTC, HarisAdzemovic commented on src/main/java/org/apache/sling/scripting/esx/Module.java
> +            if (parts[i].equals("node_modules") || parts[i].equals("esx_modules")) {
Sure thing!

2019-11-11 10:42 UTC, rombert approved these changes

2019-11-11 10:44 UTC, merged

2019-11-11 10:44 UTC, rombert commented
Merged, thanks for your contribution @HarisAdzemovic